# Generated by Django 5.0.4 on 2024-04-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_added',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_posted',
            new_name='date_added',
        ),
    ]
