# Generated by Django 5.0.4 on 2024-04-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_rename_date_added_post_date_posted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=" ", max_length=200),
            preserve_default=False,
        ),
    ]
